title: <p align="center"> Sandeep Kumar AM </p>
logo: assets/img/sandeep-pic-link.jpeg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sandeep-kumar-am-27113043/">LinkedIn</a> |
  <a href="https://github.com/sandeepam007">GitHub</a>
  
  <br>   
  Leading product management and software engineering teams on Data, Cloud and software development.
  Also handing the Big Data from real-time Ad call data.
  Worked with companies like Lowes, Mphasis, Microland and HP 
  Working in retail domain for last 6 years.
  <br>
  </p>



theme: jekyll-theme-minimal
